### ISSUE TITLE
Rewriting committer

### ISSUE THREAD

**Issue by victornoel** [davidfokkema/git-rewrite-author#13]
Hi,

Apparently this does not work if it is the committer that matches the name to rewrite.

If I have a commit with author A and committer B and rewrite from B to C, then the commit won't be rewritten!

**Comment by victornoel** [comment]
Sorry, I made a mistake when checking everything was ok, it was on origin that the old email was still there :P

**Comment by davidfokkema** [comment]
Haha, ok, thanks for closing!
