### ISSUE TITLE
Accented chars in author name

### ISSUE THREAD

**Issue by marcaube** [davidfokkema/git-rewrite-author#5]
The regex `([A-Za-z0-9\(\)\.\- ]+) <(.*)>` used to get the author name does not support accented chars like `é`. `([A-Za-z0-9\(\)\.\- \u00E9]+) <(.*)>` would work in this specific case, but it's not a generic solution and would require adding every unicode characters possible.

Would something like `(.+?)\s<(.*)>` work ?

**Comment by davidfokkema** [comment]
I tried to be specific, but the number of exceptions is growing. Ok, let's match everything. However, why the ``?``? The string ``"Dávid Fokkema <david> <davidfokkema@gmail.com>"``, albeit problematic, returns a better match using ``"(.+)\s<(.*)>"``, don't you think? Then, name, email, returns ``Dávid Fokkema <david>`` and ``davidfokkema@gmail.com``. Using the ``?``, it returns ``Dávid Fokkema`` and ``david> <davidfokkema@gmail.com``, which is not a valid email address.

**Comment by marcaube** [comment]
> However, why the `?`?

There was no reason in particular, I'm probably used to do lazy matching in my day to day.

**Comment by davidfokkema** [comment]
Thanks for reporting!

**Comment by davidfokkema** [comment]
Maybe of interest to you, @susmus7? This fix matches *all* characters, including Hungarian.

**Comment by susmus7** [comment]
Thank you for this, @davidfokkema! Much better than my quick fix :)

**Comment by davidfokkema** [comment]
You're most welcome!
