### ISSUE TITLE
Incorrect Usage

### ISSUE THREAD

**Issue by ThreaT** [davidfokkema/git-rewrite-author#6]
After running:

`$ git-rewrite-author -w "John Doe <john@localhost>" "John Doe <dearjohn@example.com>"`

I get:

`sudo: git-rewrite-author: command not found`

**Comment by davidfokkema** [comment]
You need to install the script first. Place it in a directory on your path and make it executable. Otherwise, run:

    $ python /path/to/git-rewrite-author <options>

That works, too!

**Comment by davidfokkema** [comment]
You can now install the script with:
```
$ python setup.py install
```
And then run it as an external git command:
```
$ git rewrite-author <options>
```
